### ISSUE TITLE
Full save ciklus entitásra

### ISSUE THREAD

**Issue by Hajnalics** [jaystack/DigitalTrunkShow#1]
Clientről érkező adatokra insert/update 
+ toarrayban vissza képes adni

**Comment by nochtap** [comment]
- create
- update

tud menteni draftot és publish verziót
edit siteon ha van draft azzal dolgozik
a publikus api mindíg a publikált contentel dolgozik

--------------------
kivételeket kezelni kell még, pl:
- nincs publikus verzió
- melyik deeplink legyen aktív (draft/publikált)
